function figpos()

Pos_arr = get(gcf, 'position');

disp(' ')
disp([ 'figure('...
    '''position'', [' ...
    num2str(Pos_arr(1), '%.0f') ' ' ...
    num2str(Pos_arr(1), '%.0f') ' ' ...
    num2str(Pos_arr(1), '%.0f') ' ' ...
    num2str(Pos_arr(1), '%.0f') ...
    '])'])

disp(' ')

disp(['''position'', [' ...
    num2str(Pos_arr(1), '%.0f') ' ' ...
    num2str(Pos_arr(1), '%.0f') ' ' ...
    num2str(Pos_arr(1), '%.0f') ' ' ...
    num2str(Pos_arr(1), '%.0f') ...
    ']'])

disp(' ')

end